[env:esp32-c3-devkitm-1]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino

monitor_speed = 115200
upload_speed = 460800

lib_deps =
    https://github.com/sparkfun/SparkFun_LSM6DS3_Arduino_Library.git
    https://github.com/arduino-libraries/MadgwickAHRS.git
    https://github.com/br3ttb/Arduino-PID-Library.git
    https://github.com/madhephaestus/ESP32Servo.git
    https://github.com/h2zero/NimBLE-Arduino.git
    https://github.com/mikalhart/TinyGPSPlus.git